name = "kristianazzet"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

# Env variables settes via Cloudflare Pages dashboard
# eller via wrangler secret put <NAME>
